version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5005:3000"
    env_file:
      - .env.docker
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "80:80"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
