version: '3'
services:
  backend:
    build: ./api
    ports:
      - "5002:5005"
    volumes:
      - ./api:/usr/src/app
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./app  
      dockerfile: Dockerfile 
    volumes:
      - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - "80:80"
    depends_on:
      - backend
