version: '3.8'

services:
  backend:
    build: ./api
    ports:
      - "5002:5005"  # Changed the host port to 5002
    volumes:
      - ./api:/usr/src/app
    environment:
      - NODE_ENV=production

  frontend:
    build: 
      context: ./app
      args:
        - VUE_APP_API_BASE_URL
    ports:
      - "80:80"
    environment:
      - VUE_APP_API_BASE_URL=http://backend:5002
    depends_on:
      - backend
