version: '3'

services:

  mongodb:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: schooldb      
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - app-network 

  backend:
    build: ./api
    ports:
      - "5005:5005"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - app-network 

  frontend:
    build: ./app  
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - app-network 

  nginx:
    image: nginx
    volumes:
      - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - app-network 

volumes:
  dbdata6:

networks:
  app-network:
