version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5005:3000"  
    env_file:
      - .env.docker
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo:27017/school-booking  # Connection URI to MongoDB

  frontend:
    build: ./frontend
    ports:
      - "80:80"  # Maps port 80 inside the container to port 80 on the host

  mongo:
    image: mongo:latest
    command: ["mongod", "--bind_ip_all"]  # Ensures MongoDB listens on all network interfaces
    ports:
      - "27017:27017"  # Maps port 27017 inside the container to port 27017 on the host
    volumes:
      - ~/Documents/mongo_data:/data/db  # Maps the local directory to the MongoDB data directory inside the container

volumes:
  mongo-data:
    driver: local
    driver_opts:
      type: "none"
      device: "/home/alexanderakbik/Documents/mongo_data"  # Adjust this path if needed
      o: "bind"
