services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5005:3000"
    env_file:
      - .env.docker
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo:27017/school-booking
    networks:
      - backend-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VUE_APP_API_BASE_URL=http://localhost:5005/api  # Update this based on your environment needs
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - frontend-net

  mongo:
    image: mongo:latest
    command: ["mongod", "--bind_ip_all"]
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-net

networks:
  backend-net:
  frontend-net:

volumes:
  mongo-data:
